export const textp='Este proyecto tiene como funcion ver donde y cuentas ubicaciones tienen los parqueaderos de la universidad del magdalena utilizando las tecnologias de html, css, php, booostrap, js con su base de datos en mysql y con un arquitectura mvc';
export const textfit='Este proyecto tiene como funcion tener una guia personalida de ejercicio y alimentación aún estamos mejorandolo, esta hecho con las tecnologias html, css, php, booostrap, js con su base de datos en mysql y con un arquitectura mvc ';
export const textapi='En este proyecto se ve el uso de una Api-Rest con un stack MERN creando el Api con mongodb y express, recibiendo este Api-Rest con react utlizando un arquitectura de cliente/servidor';
export const textvi=' Es una pagina para que los estudiantes de cine y audiovisules de la universidad del magdalena tengan una plataforma para mostrar sus filmes este programa esta hecho con react, laravel, mongobd sugiendo la metodología de desarrollo Devops y con una arquitectura de microserviicios';
export const but="go to proyect";
export const titlep="Proyecto Parqueadero"
export const titlefit="Proyecto Fitness"
export const titleapi="Proyecto Uso de Api-Rest"
export const titlevi="Proyecto Videosfera"
export const urlp="https://github.com/juanesGarcia/proyecto_parqueadero"
export const urlfit="https://github.com/juanesGarcia/admin-final"
export const urlvi="https://videosferas.com/"
export const urlapi="https://github.com/juanesGarcia/MongoDBAtlas-Express-"