export const textp = 'Este proyecto tiene como objetivo mostrar la disponibilidad y ubicación de los parqueaderos en la Universidad del Magdalena. Utiliza HTML, CSS, PHP, Bootstrap y JavaScript, con una base de datos MySQL y una arquitectura MVC para gestionar y presentar la información de manera eficiente.';
export const textfit = 'Este proyecto ofrece una guía personal de ejercicios y alimentación, actualmente en fase de mejora continua. Está desarrollado con HTML, CSS, PHP, Bootstrap y JavaScript, utilizando una base de datos MySQL y una arquitectura MVC para estructurar y administrar la información.';
export const textapi = 'En este proyecto se implementa una API REST utilizando el stack MERN, que incluye MongoDB y Express para la creación de la API, y React para el consumo de la API desde el cliente. La arquitectura empleada sigue el modelo cliente/servidor para una comunicación eficiente entre ambos extremos.';
export const textvi = 'Explora mi plataforma diseñada para conectar entusiastas del tatuaje con talentosos tatuadores. Utilizando tecnologías como JavaScript (React), CSS, Bootstrap, Uiverse, Redux en el frontend y Node.js (Express) con PostgreSQL en el backend, he creado un espacio interactivo. La plataforma ofrece un sistema de gestión de imágenes para perfiles, un mapa interactivo para localizar tatuadores locales y funciones de inicio de sesión y registro para una experiencia personalizada. Descubre la manera más fácil de encontrar tu tatuaje perfecto.';
export const textfrontendjr = 'Este proyecto presenta información obtenida de diversas APIs, que incluye tres entidades principales: Presidentes, Aeropuertos y Atracciones Turísticas. Cada entidad se muestra en tablas que contienen datos relevantes correspondientes. Las tecnologías utilizadas en el desarrollo del proyecto incluyen JavaScript con React, HTML y CSS. Se implementaron llamadas a APIs interrelacionadas y se gestionó la visualización de estos datos, así como la exposición de las estructuras resultantes. Además, la aplicación fue containerizada utilizando Docker, con configuraciones especificadas en los archivos Dockerfile y docker-compose.yml.';
export const textpracticante = 'Este formulario gestiona el reclutamiento de estudiantes, permitiendo la búsqueda por nombre y carrera, la asignación de calificaciones en psicotécnica y lógica, y el cálculo del promedio. Los estudiantes con calificaciones insuficientes se marcan como inactivos y reciben notificación por correo. Al finalizar la asignación de calificaciones, se determina el estudiante con el mejor promedio en cada carrera y se le notifica por correo electrónico. La información se simula localmente, aunque se supone que proviene de una API externa. Actualmente, los datos disponibles son: "Juan Pérez", "María Gutiérrez" y "Carlos Martínez", todos en "Ingeniería Informática". El código permite agregar más estudiantes según sea necesario.'
export const textperfiles = 'Este proyecto permite visualizar la información de perfiles al combinar datos de dos APIs: una que proporciona información del usuario y otra que muestra los títulos y descripciones de sus trabajos. Incluye una funcionalidad de búsqueda por nombre, así como la capacidad de eliminar trabajos específicos. Si se eliminan todos los trabajos asociados a un usuario, el perfil del usuario también se elimina. El proyecto está desarrollado utilizando JavaScript con React, HTML y CSS, y maneja la integración y manipulación de múltiples APIs para realizar operaciones como la eliminación de tareas.';
export const textia = 'Este proyecto consiste en la creación de un backend con Flask que recibe una imagen enviada por el usuario desde un frontend desarrollado con JavaScript y React. El backend analiza la imagen y devuelve al frontend el grado de similitud con las imágenes almacenadas en la base de datos. Esta API permite identificar al propietario de una marca de ganado a partir de una foto, comparándola con una base de datos de marcas y sus respectivos dueños.'
export const but="ir al proyecto";
export const titlep="Proyecto Parqueadero"
export const titlefit="Proyecto Fitness"
export const titleapi="Proyecto Uso de Api-Rest"
export const titlevi="Proyecto tattopro"
export const titlefrontendjr='Proyecto Colombia'
export const titleperfiles = 'Proyecto Perfiles'
export const titlepracticante = 'Proyecto Busqueda de Practicantes'
export const titleia='Proyecto Marca de Ganado'
export const urlp="https://github.com/juanesGarcia/proyecto_parqueadero"
export const urlfit="https://github.com/juanesGarcia/admin-final"
export const urlvi="https://tattopro.com/"
export const urlapi="https://github.com/juanesGarcia/MongoDBAtlas-Express-"
export const urlfrontendjr='https://frontend-jr.vercel.app/'
export const urlperfiles = 'https://prueba-tecnica-ebon.vercel.app'
export const urlpracticantes = 'https://conocimiento-frontend.vercel.app'
export const urlia='https://github.com/juanesGarcia/MarcasDeGanado-Ia'
export const p="pad"